BERTTrain:
  _target_: chess_gnn.tasks.BERTTrain
  model:
    _target_: chess_gnn.models.ChessBERT
    num_layers: 8
    block:
      _target_: chess_gnn.bert.TransformerBlock
      pos_emb_mode: "learned"
      hidden: 256
      attn_heads: 8
      feed_forward_hidden: 512
      norm_factory:
        _target_: chess_gnn.bert.utils.LayerNormFactory
    tokenizer:
      _target_: chess_gnn.tokenizers.SimpleChessTokenizer
    mask_handler:
      _target_: chess_gnn.bert.BERTMaskHandler
      mask_prob: 0.25
    optimizer_factory:
      _target_: chess_gnn.optimizers.LambFactory
      learning_rate: 1e-3
      weight_decay: 1e-4
    lr_scheduler_factory:
      _target_: chess_gnn.lr_schedules.CosineAnnealingWarmupFactory
      T_0: 10000
      T_mult: 2
      warmup_steps: 1000
    loss_weights:
      _target_: chess_gnn.models.BERTLossWeights
      masking: 1.0
      win_prediction: 1.0
  datamodule:
    _target_: chess_gnn.data.BERTDataModule
    data_directory: '/home/ray/datasets/chess/lumbras_2024'
    batch_size: 1024
    num_workers: 8
    mode: 'bert'
  trainer_factory:
    _target_: chess_gnn.trainer.TrainerFactory
    log_every_n_steps: 250
    max_epochs: 1
    accelerator: 'auto'
    strategy: 'ddp'
    devices: 1
    precision: "bf16-mixed"
    val_check_interval: 0.2
    num_sanity_val_steps: 1
    callbacks:
      - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      - _target_: pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        _partial_: True
        save_last: True
        save_on_train_epoch_end: True
        every_n_train_steps: 10000
