EngineTrain:
  _target_: chess_gnn.tasks.ELECTRATrain
  bert_checkpoint: '/home/ray/lightning_checkpoints/chess_bert/269807d6-7beb-4e98-9a82-4b6e611ee3f1/final.ckpt'
  model:
    _target_: chess_gnn.models.ChessELECTRA
    _partial_: True
    discriminator:
      _target_: chess_gnn.models.ChessDiscriminator
      num_layers: 12
      block:
        _target_: chess_gnn.bert.TransformerBlock
        pos_emb_mode: "learned"
        hidden: 384
        attn_heads: 8
        feed_forward_hidden: 512
        norm_factory:
          _target_: chess_gnn.bert.utils.LayerNormFactory
    mask_handler:
      _target_: chess_gnn.bert.ElectraMaskHandler
    optimizer_factory:
      _target_: chess_gnn.optimizers.LambFactory
      learning_rate: 5e-5
      weight_decay: 1e-6
    lr_scheduler_factory:
      _target_: chess_gnn.lr_schedules.CosineAnnealingWarmupFactory
      T_0: 10000
      T_mult: 2
      warmup_steps: 1000
  datamodule:
    _target_: chess_gnn.data.BERTDataModule
    data_directory: '/home/ray/datasets/chess/lumbras_2024'
    batch_size: 1024
    num_workers: 8
    mode: 'ssl'
  trainer_factory:
    _target_: chess_gnn.trainer.TrainerFactory
    log_every_n_steps: 100
    max_epochs: 1
    accelerator: 'auto'
    strategy: 'ddp_find_unused_parameters_true'
    devices: 1
    precision: "bf16-mixed"
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 1
    callbacks:
      - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      - _target_: pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        _partial_: True
        save_last: True
        save_on_train_epoch_end: True
        every_n_train_steps: 5000
