EngineTrain:
  _target_: chess_gnn.tasks.EngineTrain
  checkpoint_loader:
    _target_: chess_gnn.loaders.TransformerCheckpointLoader
    ckpt_path: "/home/ray/lightning_checkpoints/chess_transformer/a00fd243-e1b7-4ce3-997a-a7c39687ef09/last.ckpt"
  model:
    _target_: chess_gnn.models.ChessXAttnEngine
    _partial_: True
    decoder_layer:
      _target_: torch.nn.TransformerDecoderLayer
      d_model: 512
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.
      batch_first: True
    n_decoder_layers: 3
    optimizer_factory:
      _target_: chess_gnn.optimizers.LambFactory
      learning_rate: 1e-3
      weight_decay: 1e-1
      named_params: False
    lr_scheduler_factory:
      _target_: chess_gnn.schedules.CosineAnnealingWarmupFactory
      T_0: 10000
      T_mult: 10
      warmup_steps: 2500
      start_factor: 1e-8
  datamodule:
    _target_: chess_gnn.data.ChessDataModule
    data_directory: '/home/ray/datasets/chess/lumbras_2024_with_draws_transformer'
    batch_size: 1024
    num_workers: 8
    mode: 'engine'
  trainer_factory:
    _target_: chess_gnn.trainer.TrainerFactory
    log_every_n_steps: 250
    max_epochs: 2
    accelerator: 'auto'
    strategy: 'ddp'
    devices: 1
    precision: "bf16-mixed"
    val_check_interval: 2000
    limit_val_batches: 250
    num_sanity_val_steps: 10
    callbacks:
      - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      - _target_: pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'
      - _target_: chess_gnn.callbacks.TransformerFreezeCallback
        layers_to_freeze: 9
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        _partial_: True
        save_last: True
        every_n_train_steps: 10_000
        save_on_train_epoch_end: True
