EngineTrain:
  _target_: chess_gnn.tasks.EngineTrain
  checkpoint_loader:
    _target_: chess_gnn.loaders.BERTCheckpointLoader
    ckpt_path: "/home/ray/lightning_checkpoints/chess_bert/7b961c05-55bf-45a0-8090-1409a883d676/final.ckpt"
  model:
    _target_: chess_gnn.models.ChessXAttnEngine
    _partial_: True
    decoder_layer:
      _target_: torch.nn.TransformerDecoderLayer
      d_model: 384
      nhead: 4
      dim_feedforward: 768
      dropout: 0.0
      batch_first: True
    n_decoder_layers: 4
    optimizer_factory:
      _target_: chess_gnn.optimizers.LambFactory
      learning_rate: 5e-5
      weight_decay: 1e-6
    lr_scheduler_factory:
      _target_: chess_gnn.lr_schedules.CosineAnnealingWarmupFactory
      T_0: 10000
      T_mult: 2
      warmup_steps: 1000
  datamodule:
    _target_: chess_gnn.data.BERTDataModule
    data_directory: '/home/ray/datasets/chess/lumbras_2024'
    batch_size: 512
    num_workers: 8
    mode: 'engine'
  trainer_factory:
    _target_: chess_gnn.trainer.TrainerFactory
    log_every_n_steps: 100
    max_epochs: 1
    accelerator: 'auto'
    strategy: 'ddp_find_unused_parameters_true'
    devices: 1
    precision: "bf16-mixed"
    val_check_interval: 10_000
    num_sanity_val_steps: 1
    callbacks:
      - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      - _target_: pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        _partial_: True
        save_last: True
        every_n_train_steps: 2500
