ParsePGN:
  _target_: chess_gnn.tasks.ParsePGN
  parser:
    _target_: chess_gnn.data_creation.BERTLichessDatasetCreator
    pgn_file: '/home/ray/datasets/chess/lichess_db_standard_rated_2017-02.pgn'
    split:
      _target_: chess_gnn.data_creation.Split
      train: 0.9
      val: 0.05
      test: 0.05
