ParsePGN:
  _target_: chess_gnn.tasks.ParsePGN
  include_draw: True
  pgn_files:
    - '/Users/ray/datasets/chess/Carlsen.pgn'
    - '/Users/ray/Datasets/chess/Andreikin.pgn'
    - '/Users/ray/Datasets/chess/Gukesh.pgn'
    - '/Users/ray/Datasets/chess/VachierLagrave.pgn'
    - '/Users/ray/Datasets/chess/Nakamura.pgn'
  parser:
    _target_: chess_gnn.data_creation.TransformerDatasetCreator
    _partial_: True
    data_directory: '/Users/ray/datasets/chess/grandmasters'
    split:
      _target_: chess_gnn.data_creation.Split
      train: 0.9
      val: 0.05
      test: 0.05
  writer:
    _target_: chess_gnn.data_creation.TransformerHDF5DatasetBuilder
    chunk_size: 1024
