ParsePGN:
  _target_: chess_gnn.tasks.ParsePGN
  include_draw: True
  shuffle: False
  parser:
    _target_: chess_gnn.data_creation.TransformerDatasetCreator
    pgn_file: '/Users/ray/Datasets/chess/Carlsen.pgn'
    split:
      _target_: chess_gnn.data_creation.Split
      train: 0.0
      val: 0.0
      test: 1.0
  writer:
    _target_: chess_gnn.data_creation.TransformerHDF5DatasetBuilder
    chunk_size: 1024
