ShuffleData:
  _target_: chess_gnn.tasks.ShuffleData
  shuffler:
    _target_: chess_gnn.data_creation.BERTLichessDataShuffler
    input_file: '/home/ray/datasets/chess/lichess_db_standard_rated_2017-02/test/aggregated_data.txt'
