TransformerTrain:
  _target_: chess_gnn.tasks.TransformerTrain
  compile_model: True
  model:
    _target_: chess_gnn.models.ChessTransformer
    encoder:
      _target_: chess_gnn.models.ChessDiscriminator
      num_layers: 10
      block:
        _target_: chess_gnn.bert.TransformerBlock
        pos_emb_mode: "learned"
        hidden: 512
        attn_heads: 8
        feed_forward_hidden: 2048
        dropout: 0.
        norm_factory:
          _target_: chess_gnn.bert.utils.LayerNormFactory
    decoder:
      _target_: torch.nn.TransformerDecoder
      decoder_layer:
        _target_: torch.nn.TransformerDecoderLayer
        batch_first: True
        d_model: 256
        nhead: 8
        dim_feedforward: 512
        dropout: 0.
      num_layers: 4
    mask_handler:
      _target_: chess_gnn.bert.TransformerMaskHandler
      masking_ratio: &masking_ratio
        0.60
    optimizer_factory:
      _target_: chess_gnn.optimizers.LambFactory
      learning_rate: 5e-4
      weight_decay: 1e-4
    lr_scheduler_factory:
      _target_: chess_gnn.schedules.CosineAnnealingWarmupFactory
      T_0: 15_000
      T_mult: 5
      warmup_steps: 2000
    masking_schedule:
      _target_: chess_gnn.schedules.MaskingSchedule
      start_ratio: 0.15
      end_ratio: *masking_ratio
      warmup_steps: 0
  datamodule:
    _target_: chess_gnn.data.ChessDataModule
    data_directory: '/home/ray/datasets/chess/lumbras_2024_with_draws_transformer'
    batch_size: 1024
    num_workers: 8
    mode: 'transformer'
  trainer_factory:
    _target_: chess_gnn.trainer.TrainerFactory
    log_every_n_steps: 100
    max_epochs: 2
    accelerator: 'auto'
    strategy: 'ddp'
    devices: 1
    precision: "bf16-mixed"
    val_check_interval: 2000
    limit_val_batches: 250
    num_sanity_val_steps: 10
    callbacks:
      - _target_: pytorch_lightning.callbacks.TQDMProgressBar
      - _target_: pytorch_lightning.callbacks.LearningRateMonitor
        logging_interval: 'step'
      - _target_: pytorch_lightning.callbacks.ModelCheckpoint
        _partial_: True
        save_last: True
        every_n_train_steps: 10_000
        save_on_train_epoch_end: True
